// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by SqlPlus.net
//     Generated DateTime: 05-Nov-19 10:28:58 PM
//     For more information on SqlPlus.net visit http://www.SqlPlus.net
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
using System.Collections.Generic;
namespace DataAccessService.Consultorio.Models
{
    /// <summary>
    /// Result object for ContactoEmergenciaById routine.
    /// </summary>
    public class ContactoEmergenciaByIdResult
	{
        public int IdContactoEmergencia { set; get; }
        public int? IdPaciente { set; get; }
        public string Nombre { set; get; }
        public string Telefono { set; get; }
        public string Parentesco { set; get; }
    }
}