// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by SqlPlus.net
//     Generated DateTime: 05-Nov-19 10:28:58 PM
//     For more information on SqlPlus.net visit http://www.SqlPlus.net
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------

using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace DataAccessService.Consultorio.Models
{
    /// <summary>
    /// Interface for ContactoEmergenciaByIdInput object.
    /// </summary>
    public interface IContactoEmergenciaByIdInput : IValidInput
    {
        int? IdContactoEmergencia { set; get; }
    }

    /// <summary>
    /// Input object for ContactoEmergenciaById method.
    /// </summary>
    public class ContactoEmergenciaByIdInput : ValidInput, IContactoEmergenciaByIdInput
    {
        /// <summary>
        /// IdContactoEmergencia
        /// </summary>
        [Required(AllowEmptyStrings = false)]
        public int? IdContactoEmergencia { set; get; }

    }
} 