// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by SqlPlus.net
//     Generated DateTime: 01-Nov-19 11:58:04 PM
//     For more information on SqlPlus.net visit http://www.SqlPlus.net
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------

using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace DataAccessService.Consultorio.Models
{
    /// <summary>
    /// Interface for ContactoEmergenciaUpdateInput object.
    /// </summary>
    public interface IContactoEmergenciaUpdateInput : IValidInput
    {
        int? IdContactoEmergencia { set; get; }
        string Nombre { set; get; }
        string Telefono { set; get; }
        string Parentesco { set; get; }
    }

    /// <summary>
    /// Input object for ContactoEmergenciaUpdate method.
    /// </summary>
    public class ContactoEmergenciaUpdateInput : ValidInput, IContactoEmergenciaUpdateInput
    {
        /// <summary>
        /// IdContactoEmergencia
        /// </summary>
        [Required(AllowEmptyStrings = false)]
        public int? IdContactoEmergencia { set; get; }

        /// <summary>
        /// Nombre
        /// </summary>
        [MaxLength(100)]
        public string Nombre { set; get; }

        /// <summary>
        /// Telefono
        /// </summary>
        [MaxLength(50)]
        public string Telefono { set; get; }

        /// <summary>
        /// Parentesco
        /// </summary>
        [MaxLength(50)]
        public string Parentesco { set; get; }

    }
} 