// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by SqlPlus.net
//     Generated DateTime: 05-Nov-19 10:28:58 PM
//     For more information on SqlPlus.net visit http://www.SqlPlus.net
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------

using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace DataAccessService.Consultorio.Models
{
    /// <summary>
    /// Interface for GetObraSocialInput object.
    /// </summary>
    public interface IGetObraSocialInput : IValidInput
    {
        int? IdPaciente { set; get; }
    }

    /// <summary>
    /// Input object for GetObraSocial method.
    /// </summary>
    public class GetObraSocialInput : ValidInput, IGetObraSocialInput
    {
        /// <summary>
        /// Id de paciente
        /// </summary>
        [Required(AllowEmptyStrings = false)]
        public int? IdPaciente { set; get; }

    }
} 