// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by SqlPlus.net
//     Generated DateTime: 01-Nov-19 11:58:04 PM
//     For more information on SqlPlus.net visit http://www.SqlPlus.net
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------

using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace DataAccessService.Consultorio.Models
{
    /// <summary>
    /// Interface for GetObraSocialCompleteInput object.
    /// </summary>
    public interface IGetObraSocialCompleteInput : IValidInput
    {
        int? idPaciente { set; get; }
    }

    /// <summary>
    /// Input object for GetObraSocialComplete method.
    /// </summary>
    public class GetObraSocialCompleteInput : ValidInput, IGetObraSocialCompleteInput
    {
        /// <summary>
        /// IdPaciente
        /// </summary>
        [Required(AllowEmptyStrings = false)]
        public int? idPaciente { set; get; }

    }
} 