// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by SqlPlus.net
//     Generated DateTime: 05-Nov-19 10:28:58 PM
//     For more information on SqlPlus.net visit http://www.SqlPlus.net
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------

using System;
using System.Data.SqlClient;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace DataAccessService.Consultorio.Models
{
    /// <summary>
    /// Output object for GetObraSocial method.
    /// </summary>
    public class GetObraSocialOutput
    {
        public enum Returns
        {
             NotFound = 0,
             Ok = 1
        }

		public Returns ReturnValue { set; get; }

        /// <summary>
        /// List of GetObraSocialResult results.
        /// </summary>
        public List<GetObraSocialResult> ResultData { set; get; }
    }
}