// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by SqlPlus.net
//     Generated DateTime: 01-Nov-19 11:58:04 PM
//     For more information on SqlPlus.net visit http://www.SqlPlus.net
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace DataAccessService.Consultorio.Models
{
    /// <summary>
    /// Interface for PacienteUpdateInput object.
    /// </summary>
    public interface IPacienteUpdateInput : IValidInput
    {
        int? IdPaciente { set; get; }
        string DNI { set; get; }
        string Nombre { set; get; }
        string Apellido { set; get; }
        string Telefono { set; get; }
        DateTime? FechaNacimiento { set; get; }
        string Domicilio { set; get; }
        string Sexo { set; get; }
        string Localidad { set; get; }
    }

    /// <summary>
    /// Input object for PacienteUpdate method.
    /// </summary>
    public class PacienteUpdateInput : ValidInput, IPacienteUpdateInput
    {
        /// <summary>
        /// IdPaciente
        /// </summary>
        [Required(AllowEmptyStrings = false)]
        public int? IdPaciente { set; get; }

        /// <summary>
        /// DNI
        /// </summary>
        [MaxLength(50)]
        public string DNI { set; get; }

        /// <summary>
        /// Nombre
        /// </summary>
        [MaxLength(50)]
        public string Nombre { set; get; }

        /// <summary>
        /// Apellido
        /// </summary>
        [MaxLength(50)]
        public string Apellido { set; get; }

        /// <summary>
        /// Telefono
        /// </summary>
        [MaxLength(50)]
        public string Telefono { set; get; }

        /// <summary>
        /// FechaNacimiento
        /// </summary>
        public DateTime? FechaNacimiento { set; get; }

        /// <summary>
        /// Domicilio
        /// </summary>
        [MaxLength(200)]
        public string Domicilio { set; get; }

        /// <summary>
        /// Sexo
        /// </summary>
        [MaxLength(1)]
        public string Sexo { set; get; }

        /// <summary>
        /// Localidad
        /// </summary>
        [MaxLength(50)]
        public string Localidad { set; get; }

    }
} 