// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by SqlPlus.net
//     Generated DateTime: 01-Nov-19 11:58:04 PM
//     For more information on SqlPlus.net visit http://www.SqlPlus.net
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------

using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace DataAccessService.Consultorio.Models
{
    /// <summary>
    /// Interface for PacienteDeleteInput object.
    /// </summary>
    public interface IPacienteDeleteInput : IValidInput
    {
        int? IdPaciente { set; get; }
    }

    /// <summary>
    /// Input object for PacienteDelete method.
    /// </summary>
    public class PacienteDeleteInput : ValidInput, IPacienteDeleteInput
    {
        /// <summary>
        /// IdPaciente
        /// </summary>
        [Required(AllowEmptyStrings = false)]
        public int? IdPaciente { set; get; }

    }
} 