// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by SqlPlus.net
//     Generated DateTime: 05-Nov-19 10:28:58 PM
//     For more information on SqlPlus.net visit http://www.SqlPlus.net
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------

using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace DataAccessService.Consultorio.Models
{
    /// <summary>
    /// Interface for PlanObraSocialInsertInput object.
    /// </summary>
    public interface IPlanObraSocialInsertInput : IValidInput
    {
        int? IdObraSocial { set; get; }
        string Nombre { set; get; }
        bool? Habilitado { set; get; }
    }

    /// <summary>
    /// Input object for PlanObraSocialInsert method.
    /// </summary>
    public class PlanObraSocialInsertInput : ValidInput, IPlanObraSocialInsertInput
    {
        /// <summary>
        /// IdObraSocial
        /// </summary>
        public int? IdObraSocial { set; get; }

        /// <summary>
        /// Nombre
        /// </summary>
        [MaxLength(50)]
        public string Nombre { set; get; }

        /// <summary>
        /// Habilitado
        /// </summary>
        public bool? Habilitado { set; get; }

    }
} 