// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by SqlPlus.net
//     Generated DateTime: 05-Nov-19 10:28:58 PM
//     For more information on SqlPlus.net visit http://www.SqlPlus.net
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------

using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace DataAccessService.Consultorio.Models
{
    /// <summary>
    /// Interface for PlanSocialGetInput object.
    /// </summary>
    public interface IPlanSocialGetInput : IValidInput
    {
        int? IdObraSocial { set; get; }
    }

    /// <summary>
    /// Input object for PlanSocialGet method.
    /// </summary>
    public class PlanSocialGetInput : ValidInput, IPlanSocialGetInput
    {
        /// <summary>
        /// IdObraSocial
        /// </summary>
        [Required(AllowEmptyStrings = false)]
        public int? IdObraSocial { set; get; }

    }
} 