// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by SqlPlus.net
//     Generated DateTime: 05-Nov-19 10:28:58 PM
//     For more information on SqlPlus.net visit http://www.SqlPlus.net
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------

using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace DataAccessService.Consultorio.Models
{
    /// <summary>
    /// Interface for SearchPacienteInput object.
    /// </summary>
    public interface ISearchPacienteInput : IValidInput
    {
        string Searchtext { set; get; }
    }

    /// <summary>
    /// Input object for SearchPaciente method.
    /// </summary>
    public class SearchPacienteInput : ValidInput, ISearchPacienteInput
    {
        /// <summary>
        /// SearchText
        /// </summary>
        [Required(AllowEmptyStrings = false)]
        public string Searchtext { set; get; }

    }
} 