// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by SqlPlus.net
//     Generated DateTime: 01-Nov-19 11:58:04 PM
//     For more information on SqlPlus.net visit http://www.SqlPlus.net
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------

using System;
using System.Data;
using System.Data.SqlClient;
using System.Collections.Generic;
using DataAccessService.Consultorio.Models;

namespace DataAccessService.Consultorio
{
    public partial class Service
    {

        /// <summary>
        /// Builds the command object for GetAllObraSocial method
        /// </summary>
        /// <param name="cnn">The connection that will execute the procedure</param>
        /// <returns>SqlCommand ready for execution</returns>
        private SqlCommand GetGetAllObraSocialCommand(SqlConnection cnn)
        {
            SqlCommand result = new SqlCommand()
            {
                CommandType = CommandType.StoredProcedure,
                CommandText = "dbo.GetAllObraSocial",
                Connection = cnn
            };

            result.Parameters.Add(new SqlParameter()
            {
                ParameterName = "@ReturnValue",
                Direction = ParameterDirection.ReturnValue,
                SqlDbType = SqlDbType.Int,
                Scale = 0,
                Precision = 10,
                Value = DBNull.Value
            });

            return result;
        }
        private void SetGetAllObraSocialCommandOutputs(SqlCommand cmd, GetAllObraSocialOutput output)
        {
            if(cmd.Parameters[0].Value != DBNull.Value)
            {
                output.ReturnValue = (GetAllObraSocialOutput.Returns)cmd.Parameters[0].Value;
            }
        }

        private GetAllObraSocialResult GetGetAllObraSocialResultFromReader(SqlDataReader rdr)
        {
            GetAllObraSocialResult result = new GetAllObraSocialResult();

            if(!rdr.IsDBNull(0))
            {
                result.Nombre = rdr.GetString(0);
            }

            if(!rdr.IsDBNull(1))
            {
                result.Codigo = rdr.GetString(1);
            }

            result.IdObraSocial = rdr.GetInt32(2);

            return result;
        }


        private void GetAllObraSocialCommand(SqlCommand cmd, GetAllObraSocialOutput output)
        {
		
            using (SqlDataReader rdr = cmd.ExecuteReader())
            {
                output.ResultData = new List<GetAllObraSocialResult>();
                while(rdr.Read())
                {
                    output.ResultData.Add(GetGetAllObraSocialResultFromReader(rdr));
                }
                rdr.Close();
            }
            SetGetAllObraSocialCommandOutputs(cmd, output);
		}

        /// <summary>
        /// Get All obras sociales.
        /// SQL+ Routine: dbo.GetAllObraSocial - Authored by IStrficek
        /// </summary>
        public GetAllObraSocialOutput GetAllObraSocial()
        {
            GetAllObraSocialOutput output = new GetAllObraSocialOutput();
			if(sqlConnection != null)
            {
                using (SqlCommand cmd = GetGetAllObraSocialCommand(sqlConnection))
                {
                    cmd.Transaction = sqlTransaction;
                    GetAllObraSocialCommand(cmd, output);
                }
                return output;
            }
            for(int idx=0; idx <= retryOptions.RetryIntervals.Count; idx++)
            {
                if(idx > 0)
                {
                    System.Threading.Thread.Sleep(retryOptions.RetryIntervals[idx-1]);
                }
                try
                {
                    using (SqlConnection cnn = new SqlConnection(connectionString))
                    using (SqlCommand cmd = GetGetAllObraSocialCommand(cnn))
                    {
                        cnn.Open();
						GetAllObraSocialCommand(cmd, output);
                        cnn.Close();
                    }
					break;
                }
                catch(SqlException sqlException)
                {
                    bool throwException = true;

                    if(retryOptions.TransientErrorNumbers.Contains(sqlException.Number))
                    {
                        throwException = (idx == retryOptions.RetryIntervals.Count);

                        if (retryOptions.Logger != null)
                        {
                            retryOptions.Logger.Log(sqlException);
                        }
                    }
                    if(throwException)
                    {
                        throw;
                    }
                }
            }
            return output;
        }
    }
}