// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by SqlPlus.net
//     Generated DateTime: 05-Nov-19 10:28:58 PM
//     For more information on SqlPlus.net visit http://www.SqlPlus.net
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------

using System;
using System.Data;
using System.Data.SqlClient;
using System.Collections.Generic;
using DataAccessService.Consultorio.Models;

namespace DataAccessService.Consultorio
{
    public partial class Service
    {

        /// <summary>
        /// Builds the command object for GetObraSocial method.
        /// </summary>
        /// <param name="cnn">The connection that will execute the procedure.</param>
        /// <param name="input">GetObraSocialInput instance for loading parameter values.</param>
        /// <returns>SqlCommand ready for execution.</returns>
        private SqlCommand GetGetObraSocialCommand(SqlConnection cnn, IGetObraSocialInput input)
        {
            SqlCommand result = new SqlCommand()
            {
                CommandType = CommandType.StoredProcedure,
                CommandText = "dbo.GetObraSocial",
                Connection = cnn
            };

            result.Parameters.Add(new SqlParameter()
            {
                ParameterName = "@IdPaciente",
                Direction = ParameterDirection.Input,
                SqlDbType = SqlDbType.Int,
                Scale = 0,
                Precision = 10,
				Value = input.IdPaciente
            });

            result.Parameters.Add(new SqlParameter()
            {
                ParameterName = "@ReturnValue",
                Direction = ParameterDirection.ReturnValue,
                SqlDbType = SqlDbType.Int,
                Scale = 0,
                Precision = 10,
                Value = DBNull.Value
            });

            return result;
        }
        private void SetGetObraSocialCommandOutputs(SqlCommand cmd, GetObraSocialOutput output)
        {
            if(cmd.Parameters[1].Value != DBNull.Value)
            {
                output.ReturnValue = (GetObraSocialOutput.Returns)cmd.Parameters[1].Value;
            }
        }

        private GetObraSocialResult GetGetObraSocialResultFromReader(SqlDataReader rdr)
        {
            GetObraSocialResult result = new GetObraSocialResult();

            if(!rdr.IsDBNull(0))
            {
                result.Nombre = rdr.GetString(0);
            }

            if(!rdr.IsDBNull(1))
            {
                result.Codigo = rdr.GetString(1);
            }

            result.IdObraSocial = rdr.GetInt32(2);

            return result;
        }


        private void GetObraSocialCommand(SqlCommand cmd, GetObraSocialOutput output)
        {
		
            using (SqlDataReader rdr = cmd.ExecuteReader())
            {
                output.ResultData = new List<GetObraSocialResult>();
                while(rdr.Read())
                {
                    output.ResultData.Add(GetGetObraSocialResultFromReader(rdr));
                }
                rdr.Close();
            }
            SetGetObraSocialCommandOutputs(cmd, output);
		}

        /// <summary>
        /// Get pacient's Obras sociales.
        /// SQL+ Routine: dbo.GetObraSocial - Authored by IStrficek
        /// </summary>
        public GetObraSocialOutput GetObraSocial(IGetObraSocialInput input)
        {
            if (!input.IsValid())
            {
		        throw new ArgumentException("GetObraSocialInput fails validation - use the GetObraSocialInput.IsValid() method prior to passing the input argument to the GetObraSocial method.", "input");
            }
			
            GetObraSocialOutput output = new GetObraSocialOutput();
			if(sqlConnection != null)
            {
                using (SqlCommand cmd = GetGetObraSocialCommand(sqlConnection, input))
                {
                    cmd.Transaction = sqlTransaction;
                    GetObraSocialCommand(cmd, output);
                }
                return output;
            }
            for(int idx=0; idx <= retryOptions.RetryIntervals.Count; idx++)
            {
                if(idx > 0)
                {
                    System.Threading.Thread.Sleep(retryOptions.RetryIntervals[idx-1]);
                }
                try
                {
                    using (SqlConnection cnn = new SqlConnection(connectionString))
                    using (SqlCommand cmd = GetGetObraSocialCommand(cnn, input))
                    {
                        cnn.Open();
						GetObraSocialCommand(cmd, output);
                        cnn.Close();
                    }
					break;
                }
                catch(SqlException sqlException)
                {
                    bool throwException = true;

                    if(retryOptions.TransientErrorNumbers.Contains(sqlException.Number))
                    {
                        throwException = (idx == retryOptions.RetryIntervals.Count);

                        if (retryOptions.Logger != null)
                        {
                            retryOptions.Logger.Log(sqlException);
                        }
                    }
                    if(throwException)
                    {
                        throw;
                    }
                }
            }
            return output;
        }
    }
}