// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by SqlPlus.net
//     Generated DateTime: 05-Nov-19 10:28:59 PM
//     For more information on SqlPlus.net visit http://www.SqlPlus.net
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------

using System;
using System.Data;
using System.Data.SqlClient;
using System.Collections.Generic;
using DataAccessService.Consultorio.Models;

namespace DataAccessService.Consultorio
{
    public partial class Service
    {

        /// <summary>
        /// Builds the command object for PlanSocialGet method.
        /// </summary>
        /// <param name="cnn">The connection that will execute the procedure.</param>
        /// <param name="input">PlanSocialGetInput instance for loading parameter values.</param>
        /// <returns>SqlCommand ready for execution.</returns>
        private SqlCommand GetPlanSocialGetCommand(SqlConnection cnn, IPlanSocialGetInput input)
        {
            SqlCommand result = new SqlCommand()
            {
                CommandType = CommandType.StoredProcedure,
                CommandText = "dbo.PlanSocialGet",
                Connection = cnn
            };

            result.Parameters.Add(new SqlParameter()
            {
                ParameterName = "@IdObraSocial",
                Direction = ParameterDirection.Input,
                SqlDbType = SqlDbType.Int,
                Scale = 0,
                Precision = 10,
				Value = input.IdObraSocial
            });

            result.Parameters.Add(new SqlParameter()
            {
                ParameterName = "@ReturnValue",
                Direction = ParameterDirection.ReturnValue,
                SqlDbType = SqlDbType.Int,
                Scale = 0,
                Precision = 10,
                Value = DBNull.Value
            });

            return result;
        }
        private void SetPlanSocialGetCommandOutputs(SqlCommand cmd, PlanSocialGetOutput output)
        {
            if(cmd.Parameters[1].Value != DBNull.Value)
            {
                output.ReturnValue = (PlanSocialGetOutput.Returns)cmd.Parameters[1].Value;
            }
        }

        private PlanSocialGetResult GetPlanSocialGetResultFromReader(SqlDataReader rdr)
        {
            PlanSocialGetResult result = new PlanSocialGetResult();

            result.IdPlanObraSocial = rdr.GetInt32(0);

            if(!rdr.IsDBNull(1))
            {
                result.IdObraSocial = rdr.GetInt32(1);
            }

            if(!rdr.IsDBNull(2))
            {
                result.Nombre = rdr.GetString(2);
            }

            if(!rdr.IsDBNull(3))
            {
                result.Habilitado = rdr.GetBoolean(3);
            }

            return result;
        }


        private void PlanSocialGetCommand(SqlCommand cmd, PlanSocialGetOutput output)
        {
		
            using (SqlDataReader rdr = cmd.ExecuteReader())
            {
                output.ResultData = new List<PlanSocialGetResult>();
                while(rdr.Read())
                {
                    output.ResultData.Add(GetPlanSocialGetResultFromReader(rdr));
                }
                rdr.Close();
            }
            SetPlanSocialGetCommandOutputs(cmd, output);
		}

        /// <summary>
        /// Queries dbo.PlanObraSocial table.
        /// SQL+ Routine: dbo.PlanSocialGet - Authored by Ivo Strficek
        /// </summary>
        public PlanSocialGetOutput PlanSocialGet(IPlanSocialGetInput input)
        {
            if (!input.IsValid())
            {
		        throw new ArgumentException("PlanSocialGetInput fails validation - use the PlanSocialGetInput.IsValid() method prior to passing the input argument to the PlanSocialGet method.", "input");
            }
			
            PlanSocialGetOutput output = new PlanSocialGetOutput();
			if(sqlConnection != null)
            {
                using (SqlCommand cmd = GetPlanSocialGetCommand(sqlConnection, input))
                {
                    cmd.Transaction = sqlTransaction;
                    PlanSocialGetCommand(cmd, output);
                }
                return output;
            }
            for(int idx=0; idx <= retryOptions.RetryIntervals.Count; idx++)
            {
                if(idx > 0)
                {
                    System.Threading.Thread.Sleep(retryOptions.RetryIntervals[idx-1]);
                }
                try
                {
                    using (SqlConnection cnn = new SqlConnection(connectionString))
                    using (SqlCommand cmd = GetPlanSocialGetCommand(cnn, input))
                    {
                        cnn.Open();
						PlanSocialGetCommand(cmd, output);
                        cnn.Close();
                    }
					break;
                }
                catch(SqlException sqlException)
                {
                    bool throwException = true;

                    if(retryOptions.TransientErrorNumbers.Contains(sqlException.Number))
                    {
                        throwException = (idx == retryOptions.RetryIntervals.Count);

                        if (retryOptions.Logger != null)
                        {
                            retryOptions.Logger.Log(sqlException);
                        }
                    }
                    if(throwException)
                    {
                        throw;
                    }
                }
            }
            return output;
        }
    }
}