// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by SqlPlus.net
//     Generated DateTime: 05-Nov-19 10:28:58 PM
//     For more information on SqlPlus.net visit http://www.SqlPlus.net
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------

using System;
using System.Data;
using System.Data.SqlClient;
using System.Collections.Generic;
using DataAccessService.Consultorio.Models;

namespace DataAccessService.Consultorio
{
    public partial class Service
    {

        /// <summary>
        /// Builds the command object for PlanObraSocialDelete method.
        /// </summary>
        /// <param name="cnn">The connection that will execute the procedure.</param>
        /// <param name="input">PlanObraSocialDeleteInput instance for loading parameter values.</param>
        /// <returns>SqlCommand ready for execution.</returns>
        private SqlCommand GetPlanObraSocialDeleteCommand(SqlConnection cnn, IPlanObraSocialDeleteInput input)
        {
            SqlCommand result = new SqlCommand()
            {
                CommandType = CommandType.StoredProcedure,
                CommandText = "dbo.PlanObraSocialDelete",
                Connection = cnn
            };

            result.Parameters.Add(new SqlParameter()
            {
                ParameterName = "@IdPlanObraSocial",
                Direction = ParameterDirection.Input,
                SqlDbType = SqlDbType.Int,
                Scale = 0,
                Precision = 10,
				Value = input.IdPlanObraSocial
            });

            result.Parameters.Add(new SqlParameter()
            {
                ParameterName = "@ReturnValue",
                Direction = ParameterDirection.ReturnValue,
                SqlDbType = SqlDbType.Int,
                Scale = 0,
                Precision = 10,
                Value = DBNull.Value
            });

            return result;
        }
        private void SetPlanObraSocialDeleteCommandOutputs(SqlCommand cmd, PlanObraSocialDeleteOutput output)
        {
            if(cmd.Parameters[1].Value != DBNull.Value)
            {
                output.ReturnValue = (PlanObraSocialDeleteOutput.Returns)cmd.Parameters[1].Value;
            }
        }
        private void PlanObraSocialDeleteCommand(SqlCommand cmd, PlanObraSocialDeleteOutput output)
        {
            cmd.ExecuteNonQuery();
		
            SetPlanObraSocialDeleteCommandOutputs(cmd, output);
		}

        /// <summary>
        /// Deletes single row from dbo.PlanObraSocial table by identity column.
        /// SQL+ Routine: dbo.PlanObraSocialDelete - Authored by Ivo Strficek
        /// </summary>
        public PlanObraSocialDeleteOutput PlanObraSocialDelete(IPlanObraSocialDeleteInput input)
        {
            if (!input.IsValid())
            {
		        throw new ArgumentException("PlanObraSocialDeleteInput fails validation - use the PlanObraSocialDeleteInput.IsValid() method prior to passing the input argument to the PlanObraSocialDelete method.", "input");
            }
			
            PlanObraSocialDeleteOutput output = new PlanObraSocialDeleteOutput();
			if(sqlConnection != null)
            {
                using (SqlCommand cmd = GetPlanObraSocialDeleteCommand(sqlConnection, input))
                {
                    cmd.Transaction = sqlTransaction;
                    PlanObraSocialDeleteCommand(cmd, output);
                }
                return output;
            }
            for(int idx=0; idx <= retryOptions.RetryIntervals.Count; idx++)
            {
                if(idx > 0)
                {
                    System.Threading.Thread.Sleep(retryOptions.RetryIntervals[idx-1]);
                }
                try
                {
                    using (SqlConnection cnn = new SqlConnection(connectionString))
                    using (SqlCommand cmd = GetPlanObraSocialDeleteCommand(cnn, input))
                    {
                        cnn.Open();
						PlanObraSocialDeleteCommand(cmd, output);
                        cnn.Close();
                    }
					break;
                }
                catch(SqlException sqlException)
                {
                    bool throwException = true;

                    if(retryOptions.TransientErrorNumbers.Contains(sqlException.Number))
                    {
                        throwException = (idx == retryOptions.RetryIntervals.Count);

                        if (retryOptions.Logger != null)
                        {
                            retryOptions.Logger.Log(sqlException);
                        }
                    }
                    if(throwException)
                    {
                        throw;
                    }
                }
            }
            return output;
        }
    }
}