// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by SqlPlus.net
//     Generated DateTime: 05-Nov-19 10:28:59 PM
//     For more information on SqlPlus.net visit http://www.SqlPlus.net
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------

using System;
using System.Data;
using System.Data.SqlClient;
using System.Collections.Generic;
using DataAccessService.Consultorio.Models;

namespace DataAccessService.Consultorio
{
    public partial class Service
    {

        /// <summary>
        /// Builds the command object for SearchPaciente method.
        /// </summary>
        /// <param name="cnn">The connection that will execute the procedure.</param>
        /// <param name="input">SearchPacienteInput instance for loading parameter values.</param>
        /// <returns>SqlCommand ready for execution.</returns>
        private SqlCommand GetSearchPacienteCommand(SqlConnection cnn, ISearchPacienteInput input)
        {
            SqlCommand result = new SqlCommand()
            {
                CommandType = CommandType.StoredProcedure,
                CommandText = "dbo.SearchPaciente",
                Connection = cnn
            };

            result.Parameters.Add(new SqlParameter()
            {
                ParameterName = "@Searchtext",
                Direction = ParameterDirection.Input,
                SqlDbType = SqlDbType.VarChar,
                Size = 100,
				Value = input.Searchtext
            });

            result.Parameters.Add(new SqlParameter()
            {
                ParameterName = "@ReturnValue",
                Direction = ParameterDirection.ReturnValue,
                SqlDbType = SqlDbType.Int,
                Scale = 0,
                Precision = 10,
                Value = DBNull.Value
            });

            return result;
        }
        private void SetSearchPacienteCommandOutputs(SqlCommand cmd, SearchPacienteOutput output)
        {
            if(cmd.Parameters[1].Value != DBNull.Value)
            {
                output.ReturnValue = (SearchPacienteOutput.Returns)cmd.Parameters[1].Value;
            }
        }

        private SearchPacienteResult GetSearchPacienteResultFromReader(SqlDataReader rdr)
        {
            SearchPacienteResult result = new SearchPacienteResult();

            result.IdPaciente = rdr.GetInt32(0);

            if(!rdr.IsDBNull(1))
            {
                result.DNI = rdr.GetString(1);
            }

            if(!rdr.IsDBNull(2))
            {
                result.Nombre = rdr.GetString(2);
            }

            if(!rdr.IsDBNull(3))
            {
                result.Apellido = rdr.GetString(3);
            }

            if(!rdr.IsDBNull(4))
            {
                result.Telefono = rdr.GetString(4);
            }

            if(!rdr.IsDBNull(5))
            {
                result.FechaNacimiento = rdr.GetDateTime(5);
            }

            if(!rdr.IsDBNull(6))
            {
                result.Domicilio = rdr.GetString(6);
            }

            if(!rdr.IsDBNull(7))
            {
                result.Sexo = rdr.GetString(7);
            }

            if(!rdr.IsDBNull(8))
            {
                result.Localidad = rdr.GetString(8);
            }

            return result;
        }


        private void SearchPacienteCommand(SqlCommand cmd, SearchPacienteOutput output)
        {
		
            using (SqlDataReader rdr = cmd.ExecuteReader())
            {
                output.ResultData = new List<SearchPacienteResult>();
                while(rdr.Read())
                {
                    output.ResultData.Add(GetSearchPacienteResultFromReader(rdr));
                }
                rdr.Close();
            }
            SetSearchPacienteCommandOutputs(cmd, output);
		}

        /// <summary>
        /// Search for coincidences on Nombre, Apellido, DNI y Telefono.
        /// SQL+ Routine: dbo.SearchPaciente - Authored by IStrficek
        /// </summary>
        public SearchPacienteOutput SearchPaciente(ISearchPacienteInput input)
        {
            if (!input.IsValid())
            {
		        throw new ArgumentException("SearchPacienteInput fails validation - use the SearchPacienteInput.IsValid() method prior to passing the input argument to the SearchPaciente method.", "input");
            }
			
            SearchPacienteOutput output = new SearchPacienteOutput();
			if(sqlConnection != null)
            {
                using (SqlCommand cmd = GetSearchPacienteCommand(sqlConnection, input))
                {
                    cmd.Transaction = sqlTransaction;
                    SearchPacienteCommand(cmd, output);
                }
                return output;
            }
            for(int idx=0; idx <= retryOptions.RetryIntervals.Count; idx++)
            {
                if(idx > 0)
                {
                    System.Threading.Thread.Sleep(retryOptions.RetryIntervals[idx-1]);
                }
                try
                {
                    using (SqlConnection cnn = new SqlConnection(connectionString))
                    using (SqlCommand cmd = GetSearchPacienteCommand(cnn, input))
                    {
                        cnn.Open();
						SearchPacienteCommand(cmd, output);
                        cnn.Close();
                    }
					break;
                }
                catch(SqlException sqlException)
                {
                    bool throwException = true;

                    if(retryOptions.TransientErrorNumbers.Contains(sqlException.Number))
                    {
                        throwException = (idx == retryOptions.RetryIntervals.Count);

                        if (retryOptions.Logger != null)
                        {
                            retryOptions.Logger.Log(sqlException);
                        }
                    }
                    if(throwException)
                    {
                        throw;
                    }
                }
            }
            return output;
        }
    }
}